### PR TITLE
Update to 5.0-13603 (Dec 2020 to Jan 2021 report)

### PR DESCRIPTION
**Pull request by ColinKinloch**

### CODE REVIEW

**Comment by cpba** [comment]
> `x86_64-unknown-linux-gnu/bin/ld: cannot find -lusb`

Hmm, maybe we don't have the version it wants? [We're on 1.0.23](https://github.com/flathub/org.DolphinEmu.dolphin-emu/blob/master/org.DolphinEmu.dolphin-emu.json#L34)

Or maybe the linker just doesn't see it.

**Comment by ColinKinloch** [comment]
I https://github.com/dolphin-emu/dolphin/commit/14c03388b3d9ceeb40b204d19dfc407b1a4aca7d is to blame.
As far as I understand libusb.so is a compatibility wrapper for libusb-1.0.so to provide libusb-0.1 support.
I think it may have been a typo.

**Comment by cpba** [comment]
Do you think it would work if we symlinked it instead?

It'd be less likely to break on an update than another patch.

**Comment by ColinKinloch** [comment]
I gave it a quick test.
It continues to work with the USB GameCube controller adapter and a generic USB gamepads.

**Comment by ColinKinloch** [comment]
It looks like there is a merge request upstream to correct this, https://github.com/dolphin-emu/dolphin/pull/9501

**Comment by cpba** [comment]
> It continues to work with the USB GameCube controller adapter and a generic USB gamepads.

Whoah, is that what they use libusb for? I've been testing it with the bluetooth passthrough feature all along.

**Comment by ColinKinloch** [comment]
The merge request fixes libusb as a dependency for hidapi.

After a quick look at the dolphin source code:
* hidapi is used exclusively for Wiimotes presented as Bluetooth HID devices
* GC adapter, Bluetooth passthrough etc. use libusb
* Generic gamepads have no interaction with libusb

**Pull request merged**
