### PR TITLE
Fixed Wayland Support

### PR DESCRIPTION
**Pull request by iMonZ**
We have two problems:

1. Dolphin is not compatible with Wayland (So it would crash)
2. Dolphin is crashing since socket=wayland isn't set

So I added this variable to foce X in XWayland and Dolphin can now start and emulating games.

### CODE REVIEW

**Comment by cpba** [comment]
Could you please elaborate a bit further on why you need this change?

As far as I can tell it already works fine on xwayland without any changes. I routinely use it on my laptop and I've never seen it crash, it automatically changes to xwayland.

**Comment by iMonZ** [comment]
> Could you please elaborate a bit further on why you need this change?
> 
> As far as I can tell it already works fine on xwayland without any changes. I routinely use it on my laptop and I've never seen it crash, it automatically changes to xwayland.

In some distros Wayland is forced.
That’s why it’s always more secure to set the display server directly in that case X11.

**Comment by cpba** [comment]
I understand, that's quite worrying.

Do you know which distributions do this?

Do you know a simple test case I could use in the future?

**Comment by iMonZ** [comment]
> I understand, that's quite worrying.
> 
> Do you know which distributions do this?
> 
> Do you know a simple test case I could use in the future?

It’s just sets this variable globally to Wayland. (So that every QT apps runs in Wayland mode)
That’s why ever tool that’s not capable of running in Wayland should specify it with this variable that I have changed. And everything should work fine (until they actually add Wayland support)

**Comment by cpba** [comment]
Do you know what distributions do this?

So far I've tested fedora, ubuntu and a few popular ubuntu derivatives but I haven't been able to replicate the crash so far.

> It’s just sets this variable globally to Wayland. (So that every QT apps runs in Wayland mode)

Thank you, this is a very easy test case.

> btw I use manjaro with a few patches. Yuzu works wonderfully here

Is is possible that there's been some sort of confusion here? This is for dolphin, the gamecube/wii emulator, yuzu is here: https://github.com/flathub/org.yuzu_emu.yuzu

**Comment by iMonZ** [comment]
> Do you know what distributions do this?
> 
> So far I've tested fedora, ubuntu and a few popular ubuntu derivatives but I haven't been able to replicate the crash so far.
> 
> > It’s just sets this variable globally to Wayland. (So that every QT apps runs in Wayland mode)
> 
> Thank you, this is a very easy test case.
> 
> > btw I use manjaro with a few patches. Yuzu works wonderfully here
> 
> Is is possible that there's been some sort of confusion here? This is for dolphin, the gamecube/wii emulator, yuzu is here: https://github.com/flathub/org.yuzu_emu.yuzu



> Do you know what distributions do this?
> 
> So far I've tested fedora, ubuntu and a few popular ubuntu derivatives but I haven't been able to replicate the crash so far.
> 
> > It’s just sets this variable globally to Wayland. (So that every QT apps runs in Wayland mode)
> 
> Thank you, this is a very easy test case.
> 
> > btw I use manjaro with a few patches. Yuzu works wonderfully here
> 
> Is is possible that there's been some sort of confusion here? This is for dolphin, the gamecube/wii emulator, yuzu is here: https://github.com/flathub/org.yuzu_emu.yuzu

Try setting this variable globally: QT_QPA_PLATFORM=wayland 
With that you ensure that all Qt apps will run in Wayland mode.

Oh and I mean of course dolphin I have a few issues in yuzu opened that’s why I mashed the names up.

**Comment by cpba** [comment]
Do you know of any distributions that do this?

**Comment by vchernin** [comment]
I believe OpenSUSE might be one [ [1] ](https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/DOSVET4JSMIG4WUDZJD5IJNPSSSB6E5I/?sort=date) [ [2] ](https://www.reddit.com/r/openSUSE/comments/o5udwf/what_does_wayland_and_full_wayland_mean_during/h2oykzk)

**Comment by cpba** [comment]
thank you

**Pull request merged**
