### PR TITLE
Update to 5.0-14690 (Integrated GBA)

### PR DESCRIPTION
**Pull request by ColinKinloch**

### CODE REVIEW

**Comment by ColinKinloch** [comment]
The build bot cannot find a commit on the mgba submodule, it's failing at `git submodule update --init Externals/mGBA/mgba`

The build bot fails with
```
FB: Running: git ls-tree a1e806ed76e6746259a730a5db82052b53f084f1 Externals/mGBA/mgba
FB: Running: git config submodule.Externals/mGBA/mgba.url file:///srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/git/https_github.com_mgba-emu_mgba.git
FB: Running: git submodule update --init Externals/mGBA/mgba
Cloning into '/srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/build/dolphin-emu-1/Externals/mGBA/mgba'...
error: Server does not allow request for unadvertised object 9cccc5197ed73ba0a54f584d3121c27dc97405f5
Fetched in submodule path 'Externals/mGBA/mgba', but it did not contain 9cccc5197ed73ba0a54f584d3121c27dc97405f5. Direct fetching of that commit failed.
latpak-builder: Cleanup dolphin-emu^GError: module dolphin-emu: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-VHzOK5
program finished with exit code 1
```

On my local machine it continues the build
```
Cloning into '/home/ckinloch/Projects/org.DolphinEmu.dolphin-emu/.flatpak-builder/build/dolphin-emu-1/Externals/mGBA/mgba'...
remote: Enumerating objects: 55366, done.
remote: Counting objects: 100% (55366/55366), done.
remote: Compressing objects: 100% (12434/12434), done.
remote: Total 54136 (delta 42683), reused 52946 (delta 41502), pack-reused 0
Receiving objects: 100% (54136/54136), 20.36 MiB | 4.11 MiB/s, done.
Resolving deltas: 100% (42683/42683), completed with 773 local objects.
From file:///home/ckinloch/Projects/org.DolphinEmu.dolphin-emu/.flatpak-builder/git/https_github.com_mgba-emu_mgba
 * branch              9cccc5197ed73ba0a54f584d3121c27dc97405f5 -> FETCH_HEAD
Submodule path 'Externals/mGBA/mgba': checked out '9cccc5197ed73ba0a54f584d3121c27dc97405f5'
Applying patch forcexdg.patch
```

**Comment by cpba** [comment]
It's the first time I see this happen. I have no idea what may be causing it, could it be that the repo for the submodule is restricted in some way and it works on your machine because you're authenticated? 😕

As far as I can tell it's all public https://github.com/mgba-emu/mgba/commit/9cccc5197ed73ba0a54f584d3121c27dc97405f5

I'll try to rebuild just in case it was a network issue.

**Comment by cpba** [comment]
bot, build

**Comment by ColinKinloch** [comment]
Is there a docker image or something I can use to reproduce this failing build?

**Comment by ColinKinloch** [comment]
I replicated the issue with git 2.25.1 and 2.25.5.

The build works with git 2.26.0.

**Comment by cpba** [comment]
At this point I'm kinda tempted to upload a tarball to the repo and call it a day :)

I've asked for input on matrix, but now I'm going to bed, maybe somebody will come up with a workaround tomorrow.

**Comment by cpba** [comment]
bot, build

**Comment by ColinKinloch** [comment]
In trying to fix the issue this build is in a incorrect state. I'll revert it.

**Comment by cpba** [comment]
@ColinKinloch sorry I hadn't noticed the force-pushes, I was rebuilding because barthalion has graciously upgraded the git version on the builders, it should work now.

**Comment by ColinKinloch** [comment]
Seems to be working fine.

**Pull request merged**
