### PR TITLE
Update metainfo

### PR DESCRIPTION
**Pull request by Alexander-Wilms**

### CODE REVIEW

**Comment by cpba** [comment]
I'm very sorry about this, I completely forgot about your pull request.

I can't merge it as-is any longer, do you mind if I try to cherry-pick the parts that are still relevant?

**Comment by Alexander-Wilms** [comment]
Yeah, sure.

**Comment by Alexander-Wilms** [comment]
@cpba I've resolved the merge conflicts and added CI config to validate the metainfo file.

I can remove the CI if you want, but maybe the file gets upstreamed soon anyway. Maybe it could still be validated during upstream's CI.

**Comment by cpba** [comment]
> @cpba I've resolved the merge conflicts and added CI config to validate the metainfo file.

Thank you for doing this, I know I said I'd do it weeks ago.

> I can remove the CI if you want, since the file gets upstreamed soon anyway. Maybe it could still be validated during upstream's CI.

Yes I want to upstream it as soon as possible, I just have had a very stressful couple of weeks and haven't found the time to work on it.

Thank you!

**Pull request merged**
