### PR TITLE
Update to 5.0-9888 for the feb-march progress report

### PR DESCRIPTION
**Pull request by cpba**

### CODE REVIEW

**Comment by Erick555** [comment]
You have to wait for https://github.com/flathub/shared-modules/pull/58 and update shared-modules submodule afterwards.

**Comment by Erick555** [comment]
You may add `arm` to [skip-arches](https://github.com/flathub/org.DolphinEmu.dolphin-emu/blob/master/flathub.json#L2), nobody uses it anyway.

**Comment by cpba** [comment]
@Erick555 I will, do we have data on how many times a bundle has been downloaded?

I thought about removing it several times, but never did just in case somebody out there was using it.

**Comment by Erick555** [comment]
@cpba by rough estimates aarch64 and arm are ~0.03% each. i686 is ~3%. All that matters is x86_64. https://ahayzen.com/direct/flathub.html#downloadsbyarch

FYI: udev fix is merged: https://github.com/flathub/shared-modules/pull/58

**Pull request merged**
