### PR TITLE
Switch to Qt interface

### LINKED ISSUE #12: Move to Qt interface
This is just a tracking bug to say upstream has switched to Qt and we should follow.

It builds fine: https://github.com/flathub/org.DolphinEmu.dolphin-emu/tree/qt

But it crashes when running a game and has other minor rendering artifacts:

```
ASSERT failure in QCoreApplication::sendEvent: "Cannot send events to objects owned by a different thread.
Current thread 0x0x7fc7cc000b00.
Receiver '' (of type 'QCheckBox') was created in thread 0x0x19c0de0", file kernel/qcoreapplication.cpp, line 589
```

### PR DESCRIPTION
**Pull request by TingPing**
Testing would be appreciated.

Closes #12

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
Do get a crash on close and render to main window doesn't' seem to work. Maybe give it a few more weeks.

**Comment by cpba** [comment]
I built today's latest commit `54a6b0f50a2fbd6f1f85f711beb5e515f3d9e763` with this, the render to main window checkbox still doesn't do anything, but it doesn't crash on exit.

I think this can be merged.

What should be done with this afterwards? Upstream publishes several builds a day, it's clearly too much. Should this build be updated once a week, or maybe once a month to coincide with their widely shared progress reports?

**Comment by TingPing** [comment]
Building commit `472e0d55b807c7a5be847f113109ee4b38b48e80` crashes when loading at startup:

```
ASSERT failure in QVector<T>::at: "index out of range", file ../../include/QtCore/../../src/corelib/tools/qvector.h, line 423
```

**Comment by cpba** [comment]
I forgot about this PR and made a new one #14 

Tried building commit `09df03382d3607fdb865c691d58f209e8f5a589a` locally, everything seems in order. It runs fine without crashing, it doesn't crash on close, and render to main window now works in the intended way.

I think it's safe to switch now.

**Comment by TingPing** [comment]
Still crashes on exit:

```
*** Error in `dolphin-emu': double free or corruption (out): 0x00007fe7cc008320 ***
======= Backtrace: =========
/lib/libc.so.6[0x3ecfe70c4b]
/lib/libc.so.6[0x3ecfe77026]
/lib/libc.so.6[0x3ecfe7781e]
/lib/libSDL2-2.0.so.0(+0x6296f)[0x7fe800f7996f]
/lib/libSDL2-2.0.so.0(+0x38d92)[0x7fe800f4fd92]
dolphin-emu[0x8a4cc8]
dolphin-emu[0x8958c5]
dolphin-emu[0x8951f9]
dolphin-emu[0x891d5a]
dolphin-emu[0x883bd0]
dolphin-emu[0x884826]
dolphin-emu[0x884710]
dolphin-emu[0x8830d6]
dolphin-emu[0x5ebe00]
dolphin-emu[0x881a6e]
dolphin-emu[0x4738da]
dolphin-emu[0x44a114]
/lib/libc.so.6(__libc_start_main+0xf1)[0x3ecfe20291]
dolphin-emu[0x45e7fa]
```

**Comment by cpba** [comment]
While testing your conf, I couldn't get the crash on exit to happen. But I had another strange effect, the graphical settings window turned completely black.

Going back to my configuration fixed it, trying to reproduce similar settings there didn't cause the issue.

I gave up not long after that. I don't know if upstream is going to show interest in this, it could easily be a corrupted file.

**Comment by TingPing** [comment]
> But I had another strange effect, the graphical settings window turned completely black.

I've seen that in multiple Qt apps.

**Comment by cpba** [comment]
I guess it was a coincidence then, I haven't managed to have it happen again. This is rather disheartening.

If it's a Qt thing, would it be worth upgrading to the new runtime?

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
I don't use Qt stuff often, but I think I tested newer versions with the same problem (it doesn't always happen even now). Anyway I'll go ahead and merge this as my main complaints are solved.

**Pull request merged**
